export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';
export const POST_LOGIN_COMPLETE = 'POST_LOGIN_COMPLETE';

export const POST_SIGNUP = 'POST_SIGNUP';
export const POST_SIGNUP_ERROR = 'POST_SIGNUP_ERROR';
export const POST_SIGNUP_COMPLETE = 'POST_SIGNUP_COMPLETE';

export const GET_STORIES = 'GET_STORIES'
export const GET_STORIES_ERROR = 'GET_STORIES_ERROR';
export const GET_STORIES_COMPLETE = 'GET_STORIES_COMPLETE';